### ISSUE TITLE
p4w3 hackathon: Youtube presentation video is private

### ISSUE THREAD

**Issue by matevz** [kristians-kuhta/justicantus-oasis#23]
@kristians-kuhta  The submitted video URL https://youtu.be/PM63Ceg7qAw is not accessible. Please make it public so we can evaluate your project.

**Comment by kristians-kuhta** [comment]
@matevz My apologies, looks like I forgot to allow access.

It should be accessible now.

**Comment by matevz** [comment]
Works, thanks. :+1:
